### ISSUE TITLE
Bloc central de la page d'accueil

### ISSUE THREAD

**Issue by RiverSardine** [Fonctionnaire/Groupe23#129]
L'ancre est placée sur l'image, ce qui donne un résultat bizarre en responsive. ça serait mieux de la mettre sur le h1 de la page (NAO) non ?
Le texte est bizarrement coupé, il faudrait repasser la première ligne du bloc droite à la fin du bloc gauche.

**Comment by Fonctionnaire** [comment]
C'est corrigé ! Merci Nadège ;)
