### ISSUE TITLE
suggestion boutons page accueil

### ISSUE THREAD

**Issue by RiverSardine** [Fonctionnaire/Groupe23#163]
Concerne les 3 boutons en bas de page.
nous contacter => nous contacter par mail
facebook => nous suivre sur facebook 
inscription newsletter => s'inscrire à la newsletter

en version mobile si c'est trop "long", on peut ne garder que le dernier mot (mail / facebook / newsletter)

**Comment by benmorgan35** [comment]
non, c'est pas ça Nadège. c'est que les encarts sont fixes. ils ne se déforment pas. C'est ce que voulait Francisco. comme il demandait aussi qu'on ne les voit plus en mobile. sinon, ce serait éventuellement les mettre les uns en dessous des autres. c'est possible. mais je ne pense pas qu'on ait le temps de changer. comme ça ne pose aucun bug au fonctionnement ou à l'affichage. on verra s'il reste du temps si tu veux ? il reste trop de truc à faire encore pour remodifier une nouvelle fois cette page. on y a passé un temps fou déjà.

**Comment by RiverSardine** [comment]
Aucun problème pour reléguer ça à plus tard Béné ! 
Je note les trucs que je remarque, et vous décidez de la priorité ^^

**Comment by benmorgan35** [comment]
ça roule :-)
