### ISSUE TITLE
Flèche de l'écran Page d'accueil

### ISSUE THREAD

**Issue by RiverSardine** [Fonctionnaire/Groupe23#235]
Le bouton en dessous de "je participe" (la flèche vers le bas): quand je clique dessus, la page défile jusqu'au titre NAO, on ne voit pas les encarts "carte interactive" et "ajouter une observation" qui se retrouvent masqués par la barre de menu.
![fleche](https://user-images.githubusercontent.com/29752975/27995638-602be12c-64d2-11e7-9150-f2bc3867ded7.PNG)
Au premier abord ça m'a paru bizarre, donc je vous le fais remarquer. Mais si c'est un choix, ça me va et vous pouvez oublier ce commentaire.

**Comment by RiverSardine** [comment]
Je surenchéris sur le sujet, car du coup je remarque que le même type de décalage est présent si on clique sur "à propos" dans le menu "association": à la différence que là c'est le titre "NAO" qui est à moitié caché par la barre de menu
![apropos](https://user-images.githubusercontent.com/29752975/27995627-3b94d198-64d2-11e7-8352-cd767d7828e4.PNG)
Mais c'est peut-être un soucis lié à la taille de mon écran en fait ?

**Comment by Fonctionnaire** [comment]
C'est voulu comme ça. Difficile de faire un meilleur rendu pour le moment.
