### ISSUE TITLE
Traduire les datatables

### ISSUE THREAD

**Issue by benmorgan35** [Fonctionnaire/Groupe23#68]

**Comment by benmorgan35** [comment]
traduction de show et search ok en local, pas en prod

**Comment by Coubiac** [comment]
Je pense que c'est à cause de SSL. Le serveur de prod est en HTTPS et l'appel JSON de la traduction se fait en HTTP et est peut être bloqué par le navigateur. Il faut voir si on peut le trouver en https ou alors mettre le fichier JSON en local
